### ISSUE TITLE
trying to encode non-strings kills the server

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#270]
**Describe the bug**
When you have a server with a `response_output` of something other than `application/json` and respond with `this.response.body = null | true | false | undefined | some non string`, the response object tries to encode the body and dies. The error given is:

```
error: Uncaught TypeError: Invalid argument
    at TextEncoder.encode ($deno$/web/text_encoding.ts:531:19)
    at Response.send (file:///private/var/src/drashland/deno-drash/src/http/response.ts:217:31)
```

**To Reproduce**

1. create this app

```typescript
import { Drash } from "https://deno.land/x/drash/mod.ts";

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"];
  public GET() {
    this.response.body = null;
    return this.response;
  }
}

const server = new Drash.Http.Server({
  response_output: "text/html",
  logger: new Drash.CoreLoggers.ConsoleLogger({
    enabled: true,
    level: "debug",
  }),
  resources: [HomeResource],
});

server.run({
  hostname: "localhost",
  port: 1447,
});

console.log("Server listening: http://localhost:1447");

```

2. run the app and make a request in the browser to `http://localhost:1447`.

**Expected behavior**
The server doesn't die.

**Suggested Solution(s)**

```
// file: response.ts

  public generateResponse(): any {
    let contentType = this.headers.get("Content-Type");

    switch (contentType) {
      case "application/json":
        return JSON.stringify(this.body);
      case "application/xml":
      case "text/html":
      case "text/xml":
      case "text/plain":
      default:
        if (this.body === null) {
          return "null";
        }
       // if this.body == undefined then return "undefined", etc. etc.
        return this.body;
    }
  }

```

**Comment by ebebbington** [comment]
Fix is ready to go with extra tests (see branch `issue-#270-encoding-response`), but waiting to make a PR until #264 is closed (with a PR addressing it)
